//exercise 1
import "./exercise-1-1";
import "./exercise-1-2";
import "./exercise-1-3";
import "./exercise-1-4";
//exercise 2
import "./exercise-2-1";
import "./exercise-2-2";
//exercise 3
import "./exercise-3-1";
import "./exercise-3-2";
